### ISSUE TITLE
Ring outdoor Sensor cannot connect it to Homey

### ISSUE THREAD

**Issue by ericvanscheers** [daneedk/com.ring.security#10]
I already using the Ring Contact Sensor V2 and the Ring Keypad V2, works great also with Heimdall security. Now I want to connect an Outdoor sensor but cannot connect it to the Homey. 
First step "tap the pinhole button" no reaction at all. 
Already tried:
Closer to the Homey, restart Homey and update all.
Do you have any suggestions I can try?

**Comment by ericvanscheers** [comment]
After a few extra clicks on buttins of the sensor I managed to add the device. (long pressed the Orange setup button)
Don't know exactly what happend but it's connected.

**Comment by daneedk** [comment]
Hi Eric,

I must have missed your report as I only see it now you've fixed it yourself, glad you have it working.

The support for this device was requested by someone and after adding it to the app I never got a response back from the person if it worked. I don't have this sensor so was not able to test it myself. 
When adding a device, the first step is to start the remove function of the device, I guess the description on how to do that is wrong as it differ from the description of the second step, the actual adding of the device.

Could it be holding the button on the front of the device worked for the first step of resetting the device? If so I will correct the description shown in the app

**Comment by ericvanscheers** [comment]
Hi Danee,

just removed the sensor form my Homey and did a reset. So I can check the
steps.
Your guess about the description is correct .
Step one press and hold the orange button (SETUP) and releas after ~5
seconds
Step two also press and hold the orange button for ~5 seconds and the next
screen appears where you can input the pin

The pin hole is only used for resetting the device (press and hold until
the light turns red and then release)

best regards

Eric van Scheers

**Comment by daneedk** [comment]
Thanks Eric,

I've changed the description, it will be available when I publish a new version.
I will announce the publication here: [Ring Security post on Homey Community forum](https://community.homey.app/t/ring-security-extend-heimdall-with-ring-security-products/47287)

Cheers!
