### ISSUE TITLE
Version 0.2.18 ---- issues on Motion Sensors V2 ( ring ) communicating with Homeypro

### ISSUE THREAD

**Issue by grondani** [daneedk/com.ring.security#14]
Hello @daneedk 
Since the last update of your Ring Security App , done 2 days ago, Version 0.2.18, i noticed that the Motion Sensors v2 ( Ring ) stop communicating with Homey Pro, not showing any status indicator, battery status, etc. 
Let me know if i need to provide with any other information
Thank. you
Bilao

**Comment by Codeneos** [comment]
@grondani I've noticed the same. 

I am 100% certain it is related to the PR that I made last week to improve the V2 motion sensor.

I'm having 6 of them myself so currently debugging the problem. I'll create a PR once I've pinpointed the issue.

**Comment by Codeneos** [comment]
@daneedk created a new PR #15 which should fix the above. Also dropped the parameters that didn't seem to work correctly for me.

**Comment by daneedk** [comment]
@grondani  Issue has been resolved by reverting to the previous version. 
@Codeneos  will handle the new PR in the PR itself.

Closing this issue.
