### ISSUE TITLE
A fifth number in a 4-number pin code is accepted

### ISSUE THREAD

**Issue by hluhr** [daneedk/com.ring.security#2]
Let's say that you have defined the following pin code in Heimdall for a specific user:
2222

When you dis-arm with Ring keypad, the following pin codes will dis-arm:
2222 (of course)
2222? (?=any number)
Note: Adding a sixth number will NOT dis-arm

I guess that it only should be possible to dis-arm with pin code 2222.

**Comment by daneedk** [comment]
Wow, great find, well done! But actually "It's not a bug, it's a feature".
You've stumbled upon a new feature (unfinished) feature I'm working on in ***Heimdall***. 
(I figured I could work on it silently as and didn't expect anyone to find this)

This new feature let's you enter an extra digit after a valid user PIN and that extra digit will trigger a flowcard with the extra digit available as a tag. 
Such flow could be used for example to trigger a flow that will turn the kitchen lights on, useful for coming home late and getting a late night snack. Or, and I hope no-one will ever need this, Disarm with the regular PIN but add a predefined number that starts a panic flow, a sort of silent alarm, informing someone there is something wrong.

As with everything I'm working on, there is no ETA for this new function.
