### ISSUE TITLE
tamper alarm does not turn off

### ISSUE THREAD

**Issue by rijckholt** [daneedk/com.ring.security#4]
tested on dev version v0.2.1

When tamper alarm of keypad v2 is triggered it keeps showing in the homey interface 

- top right corner of app icons web /mobile (can be configured to not show or show different status)
- device information screens (current status screen and log screen).(long press on device icon mobile app for ios)

Status is not reset by laps of time or manual intervention. Not sure how this should work.

**Comment by daneedk** [comment]
Hi Onno,

The Tamper Alarm reacts to the power loss of the Keypad and will be turned off when power is restored. I've tested it several times just now and I can not reproduce your experience. Can you check and see if restoring the power turns the Tamper Alarm off for you?
