### ISSUE TITLE
Ring Door Contact not recognized

### ISSUE THREAD

**Issue by Genghes** [daneedk/com.ring.security#5]
Trying to add a Ring door contact, but when registering it it says 'No compatible Homy app found. Added as a basic Zwave device'

**Comment by Genghes** [comment]
Also same thing when adding motion sensor.
Guess they are v2?
They look a bit different than the ones in the app.

**Comment by daneedk** [comment]
Hi Torstein,

if they look different they are most likely V2 devices which are not supported by this app as I don’t have these devices and I developed this app mainly to get the Alarm Keypads working with Homey.

Unfortunately I also haven’t got the proper documentation to write support for these V2 devices without actually owning them. 

I might be able to try something but I need some information for that. Could you open the devices in the Homey app and go to Advanced Settings and make a screenshot of the Z-Wave Device Information?
I’m looking for the Device ID, Manufacturer ID, Product Type ID and Product ID for the devices. With that information I might be able to recognize the devices and see if I can write support for them.

**Comment by Genghes** [comment]
Ring Door Contact v2:
![image](https://user-images.githubusercontent.com/10722186/178445605-25a5bf36-1c27-4b45-b343-c848379d99d4.png)

**Comment by Genghes** [comment]
Ring Motion Sensor v2:
![image](https://user-images.githubusercontent.com/10722186/178446796-42feece6-e779-4278-8359-6a1e8b0a4391.png)

**Comment by Genghes** [comment]
Don't know if this is possible but here is the info for Ring Range Extender:
![image](https://user-images.githubusercontent.com/10722186/178448503-a4cc08eb-999e-484d-bbc9-16821744815f.png)

**Comment by daneedk** [comment]
Hi Torstein,

Based on the information you send me I've added the Rind Door sensor V2 to the app and uploaded it here to Github. Are you able to install the app through the CLI and test the device?

It's not complete, I'm not sure about the inclusion method and have no image for it. Also, the device icon is sketchy but If I know this works I can improve on that. 
If you run into errors running the app, please post a screenshot of the starting of the app an error here.

How to install through the CLI is explained here: https://community.homey.app/t/how-to-cli-install-method/198

**Comment by daneedk** [comment]
I've published a new test version to the Homey App Store with support for the contact sensor, could you please let me know if it works?

**Comment by Genghes** [comment]
Hi.
Really sorry for the delay in responding.
I have the Homey with the ring v2 equipment on my cabin. I will be going there in a couple of weeks.
I will test it as soon as possible.

**Comment by Pede13** [comment]
Hi,
I've tried to add my Contact Sensors V2, and it works very well, but it started some new issues.
In my Ring system the sensor ended up as "Tampered", and it wasn't possible for me to add these in Ring again.
The only way for me was to made a Hard Reset on the sensor, to bring it back to Ring System, which means that the sensor doesn't work with my Homey Pro :-)
Please let me know, if you need some more information.

**Comment by daneedk** [comment]
Hi,
Thanks for reporting Pede, glad to hear it's working with Homey!
The fact that the sensor is displayed as "Tampered" in the Ring system is kinda expected I guess. When adding the sensor to Homey it was removed from the Ring System most likely not in a way the Ring System expected. 

(If I'm not mistaken Homey forces a device reset before adding it, this was added because some users didn't reset a Z-Wave device before adding. The Ring System does it the 'old' way, expecting the user to reset a device before adding)

**Comment by daneedk** [comment]
@Genghes 
Preliminary support for the Motion Sensor is added to the new beta version (0.2.7) please test and let me know if it works.

Thanks.

**Comment by Genghes** [comment]
Hi.
I was at the cabin now and tried it with v0.2.7

I successfully went through the registration process but it still says no supported app found.

I will take the devices with me home so I will be able to test them without driving 3 hours.. 😀

**Comment by daneedk** [comment]
Thanks for reporting, I'll look into it.

**Comment by daneedk** [comment]
Found it, the ProductID on the Z-Wave Alliance website seems to be wrong compared to your screenshot. I've published a new version, can you please try again.
Oh, and I also changed the battery type used from CR2032 to 2 AA batteries, can you confirm that's right?

**Comment by Genghes** [comment]
Nice.

I can confirm the motion sensor uses 2x AA batteries.

I'm currently on a work trip and will test the new version on Wednesday when I'm home again.

**Comment by daneedk** [comment]
Yes, if it doesn’t autoupdate please install from: https://homey.app/nl-nl/app/com.ring.security/Ring-Security/test/

**Comment by Genghes** [comment]
Can confirm I got both the motion sensor and the contact sensor to connect and working.

A small thing was the text on how to enroll the motion detector.

The steps that worked for Motion Detector was:
1 - remove and insert batteries
2 - click and hold the button on the FRONT for 3-4 seconds and then let go.

Steps for Contact Sensor:
1 - Add batteries wait a couple of seconds then use a pin to bolt the hidden button for 3-4 seconds.
2 - click and hold the button on the FRONT for 3-4 seconds and then let go

**Comment by daneedk** [comment]
Great!

And thanks for explaining the inclusion steps for the devices, I’ll add that to the app!
