### ISSUE TITLE
Keypad ring v2 not working met heimdall

### ISSUE THREAD

**Issue by marksterdam** [daneedk/com.ring.security#7]
Cannot get my ring v2 keypad  to work with homey and heimdall app. Zwave network is ok. Tried to install several times. Flow test works, but keypad does nothing. What will be something to try getting it to work ??

**Comment by daneedk** [comment]
Hi Mark,

Some questions, things to test:

Did you follow these instructions: https://community.homey.app/t/ring-security-extend-heimdall-with-ring-security-products/47287/4?u=daneedekruyff

Can you explain what you mean with "Flow test works"? (Please share a screenshot of your flow)

Please restart both apps (first ***Heimdall***, then wait a bit, next ***Ring Security***) next use a pin you've configured in ***Heimdall*** and select a **Surveillance Mode**. After that, please send me a diagnostics report from both ***Heimdall*** and ***Ring Security***

Next, go to https://tools.developer.homey.app/tools/app-settings (may need to logon first and go back to that url) and select ***Heimdall***. Please see if there's any reference to information from the Ring Security app or keypad. 
(To make that page more readable, use Stylebop and the information from this post: https://community.homey.app/t/homey-flow-for-web-three-column-view-css-customization/9765/2?u=daneedekruyff)

Please post the results and the codes from the diagnostic reports here.

**Comment by marksterdam** [comment]
﻿058997f7-cb98-4237-a844-de3112241e4d

63e74eb0-37fc-4b27-a176-7fd47b35f3dd

Beste Danee,

Heb al heel veel op internet gezocht en er blijken veel problemen te zijn met keypad v2.
Ik heb alles herstart en de keypad opnieuw gekoppeld. Als ik een flow aanstuur geeft werkt het wel, alleen de keypad reageert nergens op.  Het is me nu gelukt om 1 keer alarm aan te zetten maar daarna reageerde de keypad nergens meer op. Geeft melding in de heimdall app. Geen tx errors in de log zwave.
Heb inmiddels een keypad v1 besteld om te kijken of deze wil werken. Hoop dat je wat hebt aan deze informatie. Heb alles zo ingesteld als in de forums besproken waar de problemen verholpen waren.

Met vriendelijke groet,
Mark Scheper

Verstuurd vanaf mijn iPhone


Op 20 jan. 2023 om 11:48 heeft Danee ***@***.***> het volgende geschreven:

﻿

Hi Mark,

Some questions, things to test:

Did you follow these instructions: https://community.homey.app/t/ring-security-extend-heimdall-with-ring-security-products/47287/4?u=daneedekruyff

Can you explain what you mean with "Flow test works"? (Please share a screenshot of your flow)

Please restart both apps (first Heimdall, then wait a bit, next Ring Security) next use a pin you've configured in Heimdall and select a Surveillance Mode. After that, please send me a diagnostics report from both Heimdall and Ring Security

Next, go to https://tools.developer.homey.app/tools/app-settings (may need to logon first and go back to that url) and select Heimdall. Please see if there's any reference to information from the Ring Security app or keypad.
(To make that page more readable, use Stylebop and the information from this post: https://community.homey.app/t/homey-flow-for-web-three-column-view-css-customization/9765/2?u=daneedekruyff)

Please post the results and the codes from the diagnostic reports here.

**Comment by daneedk** [comment]
Hi Mark,

(I’ll answer in English so people reading along can understand it.)

From the logs I can see your keypad is recognized in the Ring Security app and the two apps are able to verify each other and set up a connection. The keypad is also recognized in the Heimdall app as a tamper sensor, so that part is looking good.

The fact you say the keypad freezes after using it successfully sounds indeed like the same problem other users are experiencing with this device. I’m curious what firmware version your keypad is running, I’m starting to suspect a newer firmware has introduced this behaviour as the device I’m using has no such problems (and it’s a very early version)

I hope your keypad V1 version does a better job for you, for now I will close this issue.

**Comment by marksterdam** [comment]
Thanks.

A screenshot of the keypad config.
[image0.png]

Verstuurd vanaf mijn iPhone


Op 21 jan. 2023 om 10:15 heeft Danee ***@***.***> het volgende geschreven:

﻿

Hi Mark,

(I’ll answer in English so people reading along can understand it.)

From the logs I can see your keypad is recognized in the Ring Security app and the two apps are able to verify each other and set up a connection. The keypad is also recognized in the Heimdall app as a tamper sensor, so that part is looking good.

The fact you say the keypad freezes after using it successfully sounds indeed like the same problem other users are experiencing with this device. I’m curious what firmware version your keypad is running, I’m starting to suspect a newer firmware has introduced this behaviour as the device I’m using has no such problems (and it’s a very early version)

I hope your keypad V1 version does a better job for you, for now I will close this issue.
